import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {wrapper} from "../src/store/store-wrapper";


export function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <h1>Hello</h1>
      </main>
    </>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
    async ({store, req}) => {
        // Dispatch regular redux-saga action
        store.dispatch(getProjectsWithPosts());

        // Stop the saga
        store.dispatch(END);
        await store.sagaTask.toPromise();
    }
);

export default Home
